DROP TABLE IF EXISTS STOCK_INVENTORY;
CREATE TABLE STOCK_INVENTORY
(
    STOCK_NUMBER   VARCHAR(10) PRIMARY KEY,
    PURCHASE_DATE  VARCHAR(10) NOT NULL,
    PURCHASE_PRICE VARCHAR(10) NOT NULL,
    QUANTITY       INT,
    STOCK_NAME     VARCHAR(30) NOT NULL

);
insert into STOCK_INVENTORY (STOCK_NUMBER, PURCHASE_DATE, PURCHASE_PRICE, QUANTITY, STOCK_NAME)
values ('1010', '2020-05-10', '1000', 10, 'MICROSOFT');
insert into STOCK_INVENTORY (STOCK_NUMBER, PURCHASE_DATE, PURCHASE_PRICE, QUANTITY, STOCK_NAME)
values ('1001', '2020-05-20', '1000', 2, 'NIFFY');